### ISSUE TITLE
Cannot load libmkl_intel_thread.dylib

### ISSUE THREAD

**Issue by crondonm** [JuliaPy/PyPlot.jl#315]
Hi, I'm new to Julia and I am still learning. I am on MacOS 10.13 (High Sierra) and using Julia 0.6, and installed anaconda3 with python 3.6.2. Every time I run PyPlot like this:
`using PyPlot`
`plot(rand(10))`

I got the following error: 

`Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib`
`Julia has stopped: 2`

I have tried everything. I uninstalled Julia and Python, I switched back and forth between the private Conda version from PyCall and Python 3.6.  Moreover,  I plot directly from Python using matlibplot it works fine. The problem seems to be Julia. I ran out of ideas.

Any help is appreciated. 

Carlos

**Comment by iamed2** [comment]
@willtebbutt is also experiencing this, with Python 2.7 installed with Conda.jl, and El Capitan.

**Comment by stevengj** [comment]
Possibly a conflict between the BLAS libraries linked to Julia and those linked to NumPy (which is used by Matplotlib).  Are you using the standard Julia binary, built with OpenBLAS, or a Julia binary linked with MKL?

**Comment by iamed2** [comment]
Will was using the binaries (OpenBLAS). We're currently building Julia from source on his machine to see if we get the same problem.

**Comment by jonalm** [comment]
I'm having the same issue on OSX Sierra.  
```julia
julia> using PyPlot
julia> plot(rand(10))
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.
```

For what its worth:

My julia  version is `Version 0.6.0 (2017-06-19 13:05 UTC)`, installed from the `v0.6.0` branch, using `make -j 4`, and I believe the python version PyPlot tries to use, is whatever PyCall installs by default.
```julia
julia> Pkg.build("PyPlot")
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /Users/jon.alm.eriksen/.julia/v0.6/Conda/deps/usr/bin/python (Python 2.7.13) at /Users/jon.alm.eriksen/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /Users/jon.alm.eriksen/.julia/v0.6/Conda/deps/usr/lib/libpython2.7
INFO: /Users/jon.alm.eriksen/.julia/v0.6/PyCall/deps/deps.jl has not changed
INFO: /Users/jon.alm.eriksen/.julia/v0.6/PyCall/deps/PYTHON has not changed
```

**Comment by stevengj** [comment]
Is there a `libmkl_intel_thread.dylib` anywhere in `~/.julia/v0.6/Conda/deps/usr`?  Maybe the anaconda packagers didn't link things correctly so that it is just not finding the path?

**Comment by jonalm** [comment]
@stevengj I don't know if this is expected?
```
~/opt/julia > find ~/.julia/v0.6/Conda/deps/usr -name "libmkl_intel_thread.dylib"
/Users/jon.alm.eriksen/.julia/v0.6/Conda/deps/usr/lib/libmkl_intel_thread.dylib
/Users/jon.alm.eriksen/.julia/v0.6/Conda/deps/usr/pkgs/mkl-2017.0.1-0/lib/libmkl_intel_thread.dylib
/Users/jon.alm.eriksen/.julia/v0.6/Conda/deps/usr/pkgs/mkl-2018.0.0-hc285769_4/lib/libmkl_intel_thread.dylib
```
I don't know how this linking work, but is there someway to manually point to the `dylib` file?

**Comment by stevengj** [comment]
Setting `LD_LIBRARY_PATH` explicitly works around the problem, i.e.`export LD_LIBRARY_PATH=/Users/stevenj/.julia/v0.6/Conda//deps/usr/lib` before launching Julia, and then it works for me.

This seems like a problem with Anaconda.  The library paths are set up correctly if you launch the `python` executable, apparently, but not if you load `libpython` from another program (as we do in Julia).

**Comment by willtebbutt** [comment]
This solution also works for me. Thanks!

**Comment by jonalm** [comment]
Works for me too. Greatly appreciated suggestion @stevengj Thanks.

**Comment by crondonm** [comment]
It also works for me. Thank you very much!

**Comment by flamesofmoon** [comment]
Thank you very much @stevengj Works for me as well. I have struggled for two days!

**Comment by flamesofmoon** [comment]
@stevengj do you know how to set that forever? Cause every time I run Julia I have to type that command which is troublesome. Thanks a lot!

**Comment by stevengj** [comment]
@flamesofmoon , you can put it in your `~/.profile` file. 

Hopefully, we'll soon have better fix.  If nothing else, as I mentioned in ContinuumIO/anaconda-issues#6423, I can add manual `dlopen` calls in PyPlot and PyCall.  But hopefully we can get this fixed in Anaconda.

**Comment by flamesofmoon** [comment]
@stevengj Thank you! I still have the following questions:

But I don't know what it means by putting it in some designated directory. Also, I don't have the directory `~/.profile`. Could you please give me the bash command cause I just started to use terminal.

**Comment by stevengj** [comment]
```sh
echo "export LD_LIBRARY_PATH=$HOME/.julia/v0.6/Conda/deps/usr/lib" >> ~/.profile
```
then the next time you re-launch the terminal it will be set.

**Comment by flamesofmoon** [comment]
@stevengj Thank you for the reply!

I don't know why, but this time your command doesn't work on my laptop. With or without resetting the terminal, I get `Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.`

**Comment by stevengj** [comment]
A better workaround, which hopefully will get incorporated into Anaconda, is to run:
```jl
run(`install_name_tool -change @rpath/libiomp5.dylib @loader_path/libiomp5.dylib $(Pkg.dir("Conda", "deps/usr/lib/libmkl_intel_thread.dylib"))`)
```
You only need to do this once (until Conda upgrades MKL).

**Comment by anitescu** [comment]
@flamesofmoon : do you per chance have a MAC? Since El Capitan LD_LIBRARY_PATH cannot be set.

**Comment by mingwandroid** [comment]
@anitescu, conda does not require `DYLD_LIBRARY_PATH` or `DYLD_FALLBACK_LIBRARY_PATH` to be set, does julia? From what I've seen, it does not. You can set those variables anyway provided you disable `SIP`.

**Comment by stevengj** [comment]
No, Julia does not require `DYLD_LIBRARY_PATH` or similar.

In any case, I would recommend using the `install_name_tool -change` method rather than setting environment variables as a workaround until the Anaconda patch is merged into the main distro.

**Comment by anitescu** [comment]
@mingwandroid : thanks; did not mention that I hoped to not need to disable SIP.  I am a bit unclear about how it deals with certain packages, such as CPLEX which itself does require it; but do not understand it enough. 

@stevengj : there was this issue 
[issue](https://github.com/JuliaPy/PyPlot.jl/issues/315) to which I believe you also replied, maybe I misunderstood the proposed solution. 

I ended up defining the Libdl PATH and process.env.LD_ for atom by hand for the previous issue.

**Comment by flamesofmoon** [comment]
@stevengj Well, I still can't work around that. Got the same intel MKL Fatal ERROR.

Anyway, your original idea is good enough. At least I can plot now!

**Comment by zashwood** [comment]
Hi @stevengj Thanks for figuring this out. Running `export LD_Library_Path...` fixed the `Intel MKL FATAL ERROR: Cannot load `libmkl_intel_thread.dylib` problem for me.  However I have tried to run 
`install_name_tool -change @rpath/libiomp5.dylib @loader_path/libiomp5.dylib $(Pkg.dir("Conda", "deps/usr/lib/libmkl_intel_thread.dylib"))`
and I got back:
```
-bash: command substitution: line 1: syntax error near unexpected token `"Conda",'
-bash: command substitution: line 1: `Pkg.dir("Conda", "deps/usr/lib/libmkl_intel_thread.dylib")'
```
Do you know what I am doing wrong?  Thanks.

**Comment by stevengj** [comment]
@zashwood, `$(Pkg.dir(...))` is a Julia thing — it won't work in bash.  That's why I said to run it via ```run(`install_name_tool ....`)``` above.

**Comment by stevengj** [comment]
Should be fixed with the latest Conda release.

**Comment by fufjvnvnf** [comment]
I don't seem to have installed anaconda on my computer. The workaround works in the REPL but does not work in jupyter notebook for me.

**Comment by rveltz** [comment]
Hi,

I am seeing the same problem on osx. Is it fixed?

**Comment by stevengj** [comment]
The original problem was fixed more than a year ago.  I just tried updating to the latest Conda on my Mac laptop and it continues to work fine.   So maybe you are using an ancient Anaconda installation, @rveltz, and need to update.

**Comment by rveltz** [comment]
OK, I am seeing another error. I'll open an issue.

Thank you.

**Comment by milankl** [comment]
This issue came up today despite a fresh Julia and following the
> Setting `LD_LIBRARY_PATH` explicitly works around the problem, i.e.`export LD_LIBRARY_PATH=$HOME/.julia/v0.6/Conda/deps/usr/lib` before launching Julia, and then it works for me.

**Comment by wizofe** [comment]
I still have the same problem with:
- MacOS Catalina v.10.15.5
- Julia 1.5.0-rc1.0

what I get is:

```
julia> using PyPlot
[ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
INTEL MKL ERROR: dlopen(local/miniconda3/envs/cvnd3/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: local/miniconda3/envs/cvnd3/lib/libmkl_intel_thread.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.
```

**Comment by milankl** [comment]
> > Setting `LD_LIBRARY_PATH` explicitly works around the problem, i.e.`export LD_LIBRARY_PATH=$HOME/.julia/v0.6/Conda/deps/usr/lib` before launching Julia, and then it works for me.
> 
> to `.zshrc` in macos 10.15 solved the issue in the REPL but not inside Atom. Any more clues how this is caused and whether there is a more automatic way around it?

To be precise, I added
```zsh
export LD_LIBRARY_PATH=/Users/milan/.julia/conda/3/lib:$LD_LIBRARY_PATH
```
to my .zshrc. Then in Atom you can change in settings the julia-client "Julia Options" from "Basic" to "External Terminal"  for example.

**Comment by rokapre** [comment]
I am having this same issue but with just about any Python package. Following the  works in the terminal directly but not in the IDEs Atom nor VSCode.

**Comment by tlienart** [comment]
I stumbled upon this issue today on OSX with Julia 1.7, the LD_LIBRARY_PATH trick didn't work but the following did:

```
using Conda
Conda.rm("mkl")
Conda.add("nomkl")
```

I'm not sure whether both are needed but it fixed the issue for me.

**Comment by xrisk** [comment]
I’m still facing this issue.

Julia 1.6.0
macOS Big Sur 11.2.3

The LD_LIBRARY_PATH trick works for me. But I’m curious to understand why this happens in the first place. Am I using Julia incorrectly?

**Comment by George9000** [comment]
On Julia 1.6.1, macOS 10.15.7

Solution offered by tlienart worked. Thanks!

**Comment by willcoxe** [comment]
Solution provided by @tlienart also worked for me with 
Julia 1.5.3
OSX Catalina 10.15.7 
Atom 1.56.0

**Comment by TheCedarPrince** [comment]
How peculiar. I can also confirm that @tlienart's solution worked on Julia 1.6 with my mac OSX Catalina 10.15.7. Not sure why.

**Comment by KarroyWang001** [comment]
Thanks very much to @tlienart, his solution helps me a lot for my Julia 1.6.1. Still, it confuses me why it happens.

**Comment by logankilpatrick** [comment]
@tlienart is going to become famous for this one, thanks for the help! This fixed my issue on my M1 MacBook Pro with Julia 1.6

**Comment by johnnychen94** [comment]
> To be precise, I added

> `export LD_LIBRARY_PATH=/Users/milan/.julia/conda/3/lib:$LD_LIBRARY_PATH`
> to my .zshrc. Then in Atom you can change in settings the julia-client "Julia Options" from "Basic" to "External Terminal" for example.

For custom conda env settings

```julia
ENV["CONDA_JL_HOME"] = "/Users/jc/opt/miniconda3/envs/conda_jl"
ENV["PYTHON"] = "" 
```

Appending `LD_LIBRARY_PATH` with `/Users/jc/opt/miniconda3/envs/conda_jl/lib` instead of `/Users/jc/.julia/conda/3/lib`

**Comment by astrobc1** [comment]
For anyone else stuck with this error, I ended up having to manually copy the file `libiomp5.dylib` from my anaconda3 folder to the path `/Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia`. I tried copying the file `libmkl_intel_thread.1.dylib` as well into appropriate folders, modifed the `LD_LIBRARY_PATH` variable, but this was ultimately the only thing that worked.

In my case, this issue started happening after I started using a custom Python installation (the default one I usually use on my machine, not the hidden one inside ~/.julia/).

MacOS Monterey 12.3.1, Julia 1.7.2
